'use client'

import { useState } from 'react'
import { loadStripe } from '@stripe/stripe-js'
import { Elements, PaymentElement, useStripe, useElements } from '@stripe/react-stripe-js'
import { computeFee, fmtMoney, FEE_RATES, type PayMethod } from '@/lib/rentPayments'

import { stripePublishableKey } from '@/lib/stripeEnv'
import StripeModeBanner from '@/components/StripeModeBanner'

const PUBLISHABLE = stripePublishableKey()
const stripePromise = PUBLISHABLE ? loadStripe(PUBLISHABLE) : null

const APPEARANCE = {
  theme: 'stripe' as const,
  variables: { colorPrimary: '#0f172a', borderRadius: '9px', fontFamily: "'DM Sans', sans-serif" },
}

export type Payable = { kind: 'scheduled' | 'special'; id: string; label: string; amount: number }

/**
 * Pay rent — method first, then card details.
 *
 * The fee is shown before anything is entered, because a surcharge discovered
 * at the confirm step is how you lose trust in a payment flow. The figure here
 * is a preview; the server recomputes it from the database when the intent is
 * created, and the two are generated by the same function.
 */
export default function PayRentModal({
  payables, authToken, onClose, onPaid,
}: {
  payables: Payable[]
  authToken: string | null
  onClose: () => void
  onPaid: (method: PayMethod, ach: boolean) => void
}) {
  const [method, setMethod] = useState<PayMethod>('ach')
  const [clientSecret, setClientSecret] = useState<string | null>(null)
  const [starting, setStarting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const base = payables.reduce((s, p) => s + p.amount, 0)
  const quote = computeFee(base, method)

  async function start() {
    setStarting(true); setError(null)
    const res = await fetch('/api/tenant/pay', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
      },
      body: JSON.stringify({
        method,
        scheduledIds: payables.filter(p => p.kind === 'scheduled').map(p => p.id),
        specialIds: payables.filter(p => p.kind === 'special').map(p => p.id),
      }),
    })
    const json = await res.json().catch(() => ({}))
    setStarting(false)
    if (!res.ok) { setError(json.error || 'Could not start the payment.'); return }
    setClientSecret(json.clientSecret)
  }

  return (
    <div className="pay-back" onClick={onClose}>
      <style>{CSS}</style>
      <div className="pay" onClick={e => e.stopPropagation()}>
        <div className="pay-hd">
          <div>
            <div className="pay-title">Make a payment</div>
            <div className="pay-sub">{payables.length} charge{payables.length !== 1 ? 's' : ''} selected</div>
          </div>
          <button className="pay-x" onClick={onClose}>×</button>
        </div>

        <div className="pay-body">
          {/* Impossible to mistake a sandbox run for a real one. */}
          <StripeModeBanner detail style={{ marginBottom: 16 }} />

          {/* What's being paid */}
          <div className="lines">
            {payables.map(p => (
              <div key={`${p.kind}-${p.id}`} className="line">
                <span>{p.label}</span>
                <span className="line-amt">{fmtMoney(p.amount)}</span>
              </div>
            ))}
          </div>

          {!clientSecret ? (
            <>
              <div className="sec-label">How would you like to pay?</div>
              <div className="methods">
                {(['ach', 'card'] as PayMethod[]).map(m => {
                  const q = computeFee(base, m)
                  const on = method === m
                  return (
                    <button key={m} className={`method${on ? ' on' : ''}`} onClick={() => setMethod(m)}>
                      <div className="method-top">
                        <span className="method-name">
                          {m === 'ach' ? '🏦 Bank account (ACH)' : '💳 Debit or credit card'}
                        </span>
                        <span className="method-rate">{FEE_RATES[m] * 100}% fee</span>
                      </div>
                      <div className="method-sub">
                        {m === 'ach'
                          ? 'Lower fee. Takes 2–5 business days to clear.'
                          : 'Clears immediately.'}
                      </div>
                      <div className="method-total">
                        {fmtMoney(q.total)} <span>total</span>
                      </div>
                    </button>
                  )
                })}
              </div>

              <div className="totals">
                <div className="tot-row"><span>Rent &amp; charges</span><span>{fmtMoney(quote.base)}</span></div>
                <div className="tot-row">
                  <span>Processing fee ({quote.ratePct}%)</span>
                  <span>{fmtMoney(quote.fee)}</span>
                </div>
                <div className="tot-row grand"><span>Total</span><span>{fmtMoney(quote.total)}</span></div>
              </div>

              {method === 'card' && (
                <div className="tip">
                  Paying by bank account instead would cost{' '}
                  <strong>{fmtMoney(quote.fee - computeFee(base, 'ach').fee)} less</strong>.
                </div>
              )}

              {error && <div className="err">{error}</div>}

              <button className="pay-btn" onClick={start} disabled={starting || !stripePromise}>
                {starting ? 'Preparing…' : `Continue · ${fmtMoney(quote.total)}`}
              </button>
              {!stripePromise && (
                <div className="err" style={{ marginTop: 10 }}>
                  Card payments aren&apos;t configured yet — the Stripe publishable key is missing.
                </div>
              )}
            </>
          ) : (
            <Elements key={clientSecret} stripe={stripePromise} options={{ clientSecret, appearance: APPEARANCE }}>
              <PayForm
                clientSecret={clientSecret}
                authToken={authToken}
                method={method}
                total={quote.total}
                onBack={() => setClientSecret(null)}
                onPaid={() => onPaid(method, method === 'ach')}
              />
            </Elements>
          )}
        </div>
      </div>
    </div>
  )
}

function PayForm({
  clientSecret, authToken, method, total, onBack, onPaid,
}: {
  clientSecret: string
  authToken: string | null
  method: PayMethod
  total: number
  onBack: () => void
  onPaid: () => void
}) {
  const stripe = useStripe()
  const elements = useElements()
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function submit(e: React.FormEvent) {
    e.preventDefault()
    if (!stripe || !elements) return
    setSubmitting(true); setError(null)

    const { error: submitErr } = await elements.submit()
    if (submitErr) { setError(submitErr.message ?? 'Check your details.'); setSubmitting(false); return }

    const { error: confirmErr, paymentIntent } = await stripe.confirmPayment({
      elements,
      clientSecret,
      confirmParams: { return_url: window.location.href },
      redirect: 'if_required',
    })
    if (confirmErr) { setError(confirmErr.message ?? 'Payment failed.'); setSubmitting(false); return }

    // Stripe has the money; the rent rows still say "owing" until something
    // writes them. The webhook does that in production, but it is asynchronous
    // — and on a local run without `stripe listen` it never arrives at all. So
    // tell the server to check with Stripe now, and only then show success.
    await fetch('/api/tenant/pay/confirm', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
      },
      body: JSON.stringify({ paymentIntentId: paymentIntent?.id, clientSecret }),
    }).catch(() => {})   // The webhook is still the backstop — never block on this.

    onPaid()
  }

  return (
    <form onSubmit={submit}>
      <div className="sec-label" style={{ marginTop: 4 }}>
        {method === 'ach' ? 'Your bank details' : 'Card details'}
      </div>
      <PaymentElement options={{ layout: 'tabs' }} />
      {error && <div className="err" style={{ marginTop: 12 }}>{error}</div>}
      <button className="pay-btn" type="submit" disabled={!stripe || submitting}>
        {submitting ? 'Processing…' : `Pay ${fmtMoney(total)}`}
      </button>
      <button type="button" className="pay-back-btn" onClick={onBack} disabled={submitting}>
        ← Change payment method
      </button>
      {method === 'ach' && (
        <div className="tip" style={{ marginTop: 12 }}>
          Bank payments take 2–5 business days to clear. Your rent is marked as paid straight away
          and shows as clearing until it settles.
        </div>
      )}
    </form>
  )
}

const CSS = `
  .pay-back { position: fixed; inset: 0; background: rgba(15,23,42,0.6); z-index: 500; display: flex; align-items: center; justify-content: center; padding: 20px; font-family: 'DM Sans', sans-serif; }
  .pay { background: #fff; border-radius: 16px; width: 100%; max-width: 460px; max-height: 92vh; display: flex; flex-direction: column; overflow: hidden; }
  .pay-hd { display: flex; align-items: flex-start; justify-content: space-between; padding: 18px 20px 14px; border-bottom: 1px solid #f1f5f9; }
  .pay-title { font-size: 17px; font-weight: 700; color: #0f172a; }
  .pay-sub { font-size: 12px; color: #94a3b8; margin-top: 2px; }
  .pay-x { background: none; border: none; font-size: 24px; line-height: 1; color: #94a3b8; cursor: pointer; }
  .pay-body { padding: 18px 20px 22px; overflow: auto; }

  .lines { border: 1px solid #eef2f7; border-radius: 10px; overflow: hidden; margin-bottom: 18px; }
  .line { display: flex; justify-content: space-between; gap: 12px; padding: 10px 13px; font-size: 13px; color: #334155; }
  .line + .line { border-top: 1px solid #f8fafc; }
  .line-amt { font-weight: 700; color: #0f172a; white-space: nowrap; }

  .sec-label { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.6px; color: #94a3b8; margin-bottom: 9px; }

  .methods { display: flex; flex-direction: column; gap: 9px; margin-bottom: 16px; }
  .method { text-align: left; background: #fff; border: 1.5px solid #e2e8f0; border-radius: 11px; padding: 13px 15px; cursor: pointer; font-family: inherit; }
  .method:hover { border-color: #cbd5e1; }
  .method.on { border-color: #0f172a; border-width: 2px; padding: 12px 14px; background: #fafbfc; }
  .method-top { display: flex; align-items: center; justify-content: space-between; gap: 10px; }
  .method-name { font-size: 14px; font-weight: 600; color: #0f172a; }
  .method-rate { font-size: 11px; font-weight: 700; color: #64748b; background: #f1f5f9; padding: 2px 8px; border-radius: 20px; }
  .method-sub { font-size: 11.5px; color: #94a3b8; margin-top: 3px; }
  .method-total { font-size: 15px; font-weight: 700; color: #0f172a; margin-top: 7px; }
  .method-total span { font-size: 11px; font-weight: 500; color: #94a3b8; }

  .totals { border-top: 1px solid #f1f5f9; padding-top: 12px; margin-bottom: 14px; }
  .tot-row { display: flex; justify-content: space-between; font-size: 13px; color: #475569; padding: 4px 0; }
  .tot-row.grand { font-size: 16px; font-weight: 700; color: #0f172a; border-top: 1px solid #e2e8f0; margin-top: 6px; padding-top: 10px; }

  .tip { background: #ecfdf5; border: 1px solid #a7f3d0; color: #065f46; border-radius: 9px; padding: 10px 12px; font-size: 12px; line-height: 1.5; margin-bottom: 14px; }

  .err { background: #fef2f2; border: 1px solid #fecaca; color: #991b1b; border-radius: 8px; padding: 10px 12px; font-size: 12.5px; }

  .pay-btn { width: 100%; margin-top: 16px; background: #0f172a; color: #34d399; border: none; border-radius: 10px; padding: 14px; font-size: 15px; font-weight: 700; cursor: pointer; font-family: inherit; }
  .pay-btn:disabled { opacity: 0.55; cursor: not-allowed; }
  .pay-back-btn { width: 100%; margin-top: 9px; background: none; border: none; color: #64748b; font-size: 12.5px; font-weight: 600; cursor: pointer; font-family: inherit; }
`
